### ISSUE TITLE
#01 データベースの設計をする

### ISSUE THREAD

**Issue by yamaso** [gaiax/my_gaman_app#1]
以下の図を元に、Firebaseで用いるデータベースの設計を行う
![バックエンド](https://user-images.githubusercontent.com/44431841/107454161-dc924180-6b8f-11eb-956f-321d7d3f8c0c.png)

データベース設計
---
<img width="672" alt="スクリーンショット 2021-03-17 10 41 39" src="https://user-images.githubusercontent.com/44431841/111401861-7740eb80-870d-11eb-863e-b827a2eb2aa9.png">

**Comment by yamaso** [comment]
暫定データベース設計
---
<img width="780" alt="スクリーンショット 2021-02-25 18 55 54" src="https://user-images.githubusercontent.com/44431841/109136178-318ea400-779b-11eb-8e46-0075944826da.png">

※ cheer　は、Twitterでいう「いいね」機能のようなもの
※登録、投稿されるごとにドキュメントが増えていく

**Comment by sohismyson** [comment]
## posts
- この名前だと、今後投稿するコンテンツがあった場合にかぶると思うので`我慢`を表す直接的な命名がよいと思います。（今後と書きましたが、今回そこまでやらないにしろ考慮が必要な範囲だと考えます）
- posts内でのemailの用途はなんでしょうか
- usernameとemailですが、他のコレクションをリファレンスで保存できるのでuserIdのような形でもっておいてもよいと思います
- dateの用途はなんでしょうか
  - 我慢したもののリスト表示のためであれば、同日に我慢した場合はどのようになりますか
- cheer
  - 誰から、いつとかは必要ないですか

## users
- Firebase Authenticationを利用するとおもうのですが、そことの紐付けできてますか
- チアの機能があると思うのですが、ユーザーどうしのコミュニケーションのために他の画像やプロフなどの要素は必要ないですか
- usersだけの話ではないのですが、作成された日時は往々にして利用するので持っておいたほうがよいと思います。`createdAt`的な。

## その他
- 目標のデータはどのようにして保存しますか
- モックで`2ヶ月で5kg痩せる`とありますが、期間の設定はありますか
- 1ユーザーの目標は1つですか？完了した次、目標設定はどのようになりますか
- 目標の達成、未達はどのように表現しますか

そのほか足りないものはありませんか？？

**Comment by yamaso** [comment]
こちら、issue本文の方でデータベース設計を変更しました。

変更点
---
- postsの名前をgamansに変更
   - dateはcreatedAtに変更
   - emailは特に利用しないので、削除
- Auth機能を利用するので、usersテーブルは削除
- cheerに関しては、モチベーションの応援を可視化する目的のため、α版では「誰から」などの通知は行わない。
- 目標のデータは基本的にローカルのアプリケーション内で定義するようにする予定だったが、今後「過去に達成した目標」を確認する機能を追加する可能性もあるので、goalコレクションを追加。欲しいものの画像はFirebase上に保存するため、「wantThing_img」にURLを保存しておく。
   - **こちらは必要性について要検討**
 
目標はテキストベースで設定され、並行させることはできないようにしようと思います。
達成時の挙動については、今後追加で考えます。

**Comment by sohismyson** [comment]
@yamaso 
いま見直していて気づいたことがあったので確認お願いします。

> Auth機能を利用するので、usersテーブルは削除
- ユーザー名はどこで管理しますか。

> cheerに関しては、モチベーションの応援を可視化する目的のため、α版では「誰から」などの通知は行わない。
- 通知が行われないにしても誰が実行したかは保存したほうがいいと考えます。

----
もうひとつ
`wantThing_img` のような名前は色々な記法が混ざっていて認識しにくいので、どれかに統一しましょう。
参考: https://qiita.com/yimajo/items/a3fac0026c07ec538fc2

最近うちの会社だとローワーキャメルケースで記載することが多いので、それに揃えるとよいと思います。

**Comment by yamaso** [comment]
取り急ぎ、
- **ユーザ名の管理**について。
FirebaseのAuthenticationを直接操作することで管理できそうです。ユーザ名の設定、アカウント確認メールの送信、アカウント削除などもできそうです。
https://firebase.google.com/docs/auth/web/manage-users?hl=ja#update_a_users_profile
@sohismyson

**Comment by yamaso** [comment]
cheerに関して、issueの方でデータベース設計を更新しました。
