### ISSUE TITLE
メインページのUIをベータ版用にブラッシュアップ

### ISSUE THREAD

**Issue by yamaso** [gaiax/my_gaman_app#16]
## 概要
UIのモックアップ感が拭えていないので、再考して、ユーザが使いやすいUIを目指し、リニューアルする。

## 受け入れ条件
- [x] 見た目がよくなったか
- [x] 使いやすいか
- [x] 色彩が統一されて見える。

## 参考
issue: #5 #6 
プロトタイプ: https://xd.adobe.com/view/2869e3f8-17de-4c52-bb40-c25874b1e1b9-7d3a/
その他:

**Comment by yamaso** [comment]
ブラッシュアップ案
---
- ￥がフォントの影響で / になっています。
- メインである、水が溜まっていくUIが目立つようにしました。
- 「ディスプレイ」の部分に商品名が入ります。
![iOS の画像](https://user-images.githubusercontent.com/44431841/111247272-05a06900-864b-11eb-86cb-28b1423092dd.jpg)

**Comment by sohismyson** [comment]
@yamaso 

> メインである、水が溜まっていくUIが目立つようにしました。

メインの要素なので、よいですね！

いくつかフィードバックします。全て対応する必要ないので、取捨選択してください。
- ローマ字、英語、日本語が混ざっていてわかりにくいです。それぞれ意図を持って利用するのがよいと思います。
- 右利きの人であれば、右下をもって操作するとおもうので、GAMANボタンは持ったまま操作できるような位置が良いとおもいました。
- 文字の左寄せとセンタリングは意図を持って利用したいです。
- 水が溜まっていくのを目立たせたのはよいのですが、我慢したあとのご褒美がモチベにつながると思います。ご褒美画像もどうにか目立たせ、「これがゲットできるから頑張ろう！」を促せたらよいですね。さらに、画面の高さは端末によって変わるので、見切れてもいい要素かどうか、どこまでは絶対に表示させていたいかも併せて検討したほうがよさそうです。
- ボタンの色と他の背景色が同じで、ボタンであることが認識しにくいです。（エレベーションの設定はされてるのですが、弱いです）

**Comment by yamaso** [comment]
ありがとうございます！

- GAMANがローマ字でややこしいので、[SAVE]に変更したいと思います。
- SAVEボタンが押しやすいように、やはりGOALと水がたまるUIの位置は元に戻そうと思います。
- ボタンに関しては微調整します。

**Comment by yamaso** [comment]
ブラッシュアップ案２
---
変更点

------
- 20代男性を意識し、シンプルで寒色を基調としたUIに。
- 欲しいモノを買うための疑似貯金がメインの機能であることをより意識したデザインへ。
- 青系の色をアクセントとして使い、すっきりとした健康的で、スマートなイメージへ。
- 右上の三点リーダーで「目標の変更」が可能
- 上部に、目標として登録したAmazonリンクから取得した「商品画像」と、そこに重ねる形で目標を表示。（目標を重ねるかどうかは迷っています。）
- 上部目標設定した欲しいモノの画像は、SliverAppBarで実装することで、スクロールと同時に縮小する。
- フローティングアクションボタンで我慢するモノを追加（貯金）

主に、貯金アプリや健康維持アプリのUIなどを参考にしました。
![GamanApp_Ver2](https://user-images.githubusercontent.com/44431841/112959688-a419e780-917e-11eb-8f22-4e201dd76409.png)

**Comment by yamaso** [comment]
@sohismyson 一度確認をお願いいたします！

**Comment by yamaso** [comment]
XDで操作感などを確かめつつ、実装に変更を加えていきます。

**Comment by yamaso** [comment]
メモ
- 文字の縁はなし
- 色の工夫
- 背景を水にしておく？

**Comment by yamaso** [comment]
ブラッシュアップ案3
---
変更点
- 色彩をGoogleのマテリアルデザインに合わせ、再構成
- レイアウトを微調整
- 文字の縁は無くし、類似色でまとまりのあるデザインへ。
![GamanApp_Ver3](https://user-images.githubusercontent.com/44431841/114534456-f8968a00-9c89-11eb-8e02-f0d6840f5bb6.jpg)

**Comment by yamaso** [comment]
<img width="1015" alt="UI_test@2x-8" src="https://user-images.githubusercontent.com/44431841/116055488-b91f6300-a6b7-11eb-886f-ab415a5ef756.png">

**Comment by yamaso** [comment]
変更完了。
<img width="392" alt="スクリーンショット 2021-05-11 2 51 54" src="https://user-images.githubusercontent.com/44431841/117702718-da2d9b00-b203-11eb-9ec3-731c4721a593.png">
