### ISSUE TITLE
UIや見た目の挙動を実装していく

### ISSUE THREAD

**Issue by yamaso** [gaiax/my_gaman_app#4]
作ったモックアップから、メイン画面のUIを実装していく

**Comment by yamaso** [comment]
子issue: 
#5 
#6 
#7

**Comment by sohismyson** [comment]
@yamaso 
このissueは何をするためのissueでしょうか。画面ごとや機能ごとにissueがあればよいようにみえます。

あと、全体的な話ですが、モックアップが完全ではないので、抜け漏れがでそうです。
- ユーザー登録
- サインイン
- 目標設定
- 目標の編集
- 目標達成後どうなるか
  - 次の目標（並行して目標つくれるのかも検討必要）
  - 過去の目標
- チアの仕組み（twitterのいいねとのことなので、それを前提に）
  - ユーザー間のつながりをどこで表示しますか
  - コミュニケーションなので、ユーザー名やユーザー画像、プロフィールのようなものは不要ですか

このあたり、いかがですか？

**Comment by yamaso** [comment]
ユーザー登録や、サインインの機能は、 #3 のように先に実装してしまいました。
なので、これはこのまま使い、目標設定や編集、達成後、チアの仕組みに関しては追加でissueを立てたいと思います。
