### ISSUE TITLE
メインページのUI作成

### ISSUE THREAD

**Issue by yamaso** [gaiax/my_gaman_app#5]
親issue： #4 
参考プロトタイプ：https://xd.adobe.com/view/2869e3f8-17de-4c52-bb40-c25874b1e1b9-7d3a/
作業ブランチ：yamamoto/make_HomePage

概要
---
ログイン後のホーム画面にて、現在自分が立てている目標やご褒美を確認することができ、視覚的にいくら分の我慢が達成されているかを、水が溜まっていくようなUIで直感的に確認することができる。

このissueでは、メインページのUIを実装する。

実装チェックリスト
---

- [x] 自分の目標　＝＞（Text, 変数で実装）
- [x] 欲しいものの確認(画像と商品名）＝＞（ImageやText, 変数で実装 ）
- [x] 欲しいものに対し、自分がいくら分我慢したかの進捗が表示されている。（WaveメーターのようなUI）＝＞（issue説明の備考参考）
  - [x] これまでに我慢した金額が表示されている
  - [x] 目標金額が表示されている
  - [x] 水がたまっているようなUIで直感的に進捗を把握できる
- [x] 買い食いなどを我慢（登録）する画面に遷移することができる。　＝＞（Raiseボタンで実装）
- [x] 目標の変更ができる。（スターフロートアイコンになっているが、適宜変更する。）
- [x] 他のページにアクセスできるドロワーメニューが表示できる

---

該当画面
<img width="272" alt="スクリーンショット 2021-02-25 16 03 51" src="https://user-images.githubusercontent.com/44431841/109115940-1adc5300-7783-11eb-8965-270b0fe6483d.png">

---
**備考**
中央UIデザイン参考URL: https://www.youtube.com/watch?v=AKP7KY0Ckis
データベースの連携は、のちのissueで行う

**Comment by sohismyson** [comment]
どういった画面なのかの説明。
何を実装するかのチェックボックスの、リストがあるとなお良いとおまいます。

**Comment by yamaso** [comment]
わかりました、洗い出し後、追記します。

**Comment by yamaso** [comment]
実装チェックリスト
---

- [ ] 自分の目標　＝＞（Text, 変数で実装）
- [ ] 欲しいものの確認(画像と商品名）＝＞（ImageやText, 変数で実装）
- [ ] 欲しいものに対し、自分がいくら分我慢したかの確認。（WaveメーターのようなUI）＝＞（issue説明の備考参考）
- [ ] 買い食いなどを我慢（登録）する画面に遷移するボタン　＝＞（Raiseボタンで実装）
- [ ] 目標の変更（スターフロートアイコンになっているが、適宜変更する。）

**Comment by sohismyson** [comment]
@yamaso 
チェックリストがコメントにあると、作業時も確認するときも言ったり来たりになるので、コアな内容はもとのissueを編集して追記がよいと思います。
